# Model configuration for PalmFusion project
model:
  name: yolov12
  pretrained: true
  backbone: yolov12-p2
  neck: PAN
  head: YOLOv12Head

# Training parameters
train:
  epochs: 150
  optimizer: AdamW
  lr0: 0.001
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1

# Feature fusion parameters
fusion:
  palm_print_weight: 0.2  # 20% weight for palm print features
  palm_vein_weight: 0.8   # 80% weight for palm vein features
  fusion_method: 'weighted_sum'

# Preprocessing
preprocessing:
  palm_print:
    method: 'real_esrgan'
    scale: 4
    denoise_strength: 0.5
  palm_vein:
    method: 'gamma_correction'
    gamma: 1.5
    contrast_limit: 3.0

# Loss configuration
loss:
  box: 0.05
  cls: 0.5
  dfl: 1.0
  
# Testing/Inference
test:
  conf_thres: 0.25
  iou_thres: 0.45
  max_det: 300
  
# Save settings
save:
  save_period: 10
  save_best: true 